// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.clashmiao.clashmiao.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object BoxApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * sing-box 调用入参 / 出参承载体。
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class StartRequest (
  val configPath: String,
  val profileName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): StartRequest {
      val configPath = pigeonVar_list[0] as String
      val profileName = pigeonVar_list[1] as String
      return StartRequest(configPath, profileName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      configPath,
      profileName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is StartRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConfigOptions (
  val jsonOptions: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConfigOptions {
      val jsonOptions = pigeonVar_list[0] as String
      return ConfigOptions(jsonOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      jsonOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConfigOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SelectOutboundRequest (
  val groupTag: String,
  val outboundTag: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SelectOutboundRequest {
      val groupTag = pigeonVar_list[0] as String
      val outboundTag = pigeonVar_list[1] as String
      return SelectOutboundRequest(groupTag, outboundTag)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      groupTag,
      outboundTag,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SelectOutboundRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ValidateConfigRequest (
  val path: String,
  val tempPath: String,
  val debug: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ValidateConfigRequest {
      val path = pigeonVar_list[0] as String
      val tempPath = pigeonVar_list[1] as String
      val debug = pigeonVar_list[2] as Boolean
      return ValidateConfigRequest(path, tempPath, debug)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      tempPath,
      debug,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ValidateConfigRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ValidateConfigResult (
  /** `null` 表示成功；非空字符串为人类可读错误。 */
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ValidateConfigResult {
      val error = pigeonVar_list[0] as String?
      return ValidateConfigResult(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ValidateConfigResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class InstalledApp (
  val packageName: String,
  val appName: String,
  val isSystemApp: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): InstalledApp {
      val packageName = pigeonVar_list[0] as String
      val appName = pigeonVar_list[1] as String
      val isSystemApp = pigeonVar_list[2] as Boolean
      return InstalledApp(packageName, appName, isSystemApp)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      packageName,
      appName,
      isSystemApp,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is InstalledApp) {
      return false
    }
    if (this === other) {
      return true
    }
    return BoxApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class BoxApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          StartRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConfigOptions.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SelectOutboundRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ValidateConfigRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ValidateConfigResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          InstalledApp.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is StartRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ConfigOptions -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is SelectOutboundRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is ValidateConfigRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ValidateConfigResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is InstalledApp -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Dart 调原生：sing-box 生命周期 + 状态变更。
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface BoxHostApi {
  fun initialize(callback: (Result<Unit>) -> Unit)
  fun setup(baseDir: String, workingDir: String, tempDir: String, debug: Boolean, callback: (Result<Unit>) -> Unit)
  fun validateConfig(req: ValidateConfigRequest, callback: (Result<ValidateConfigResult>) -> Unit)
  fun changeConfigOptions(options: ConfigOptions, callback: (Result<Unit>) -> Unit)
  fun start(req: StartRequest, callback: (Result<Unit>) -> Unit)
  fun stop(callback: (Result<Unit>) -> Unit)
  fun restart(req: StartRequest, callback: (Result<Unit>) -> Unit)
  fun selectOutbound(req: SelectOutboundRequest, callback: (Result<Unit>) -> Unit)
  fun urlTest(groupTag: String, callback: (Result<Unit>) -> Unit)
  fun generateFullConfig(path: String, callback: (Result<String?>) -> Unit)
  fun clearLogs(callback: (Result<Unit>) -> Unit)
  fun getInstalledApps(callback: (Result<List<InstalledApp>>) -> Unit)
  fun getAppIconBase64(packageName: String, callback: (Result<String?>) -> Unit)

  companion object {
    /** The codec used by BoxHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      BoxApiPigeonCodec()
    }
    /** Sets up an instance of `BoxHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BoxHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.setup$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val baseDirArg = args[0] as String
            val workingDirArg = args[1] as String
            val tempDirArg = args[2] as String
            val debugArg = args[3] as Boolean
            api.setup(baseDirArg, workingDirArg, tempDirArg, debugArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.validateConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as ValidateConfigRequest
            api.validateConfig(reqArg) { result: Result<ValidateConfigResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BoxApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.changeConfigOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as ConfigOptions
            api.changeConfigOptions(optionsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as StartRequest
            api.start(reqArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stop{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.restart$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as StartRequest
            api.restart(reqArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.selectOutbound$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reqArg = args[0] as SelectOutboundRequest
            api.selectOutbound(reqArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.urlTest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val groupTagArg = args[0] as String
            api.urlTest(groupTagArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.generateFullConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.generateFullConfig(pathArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BoxApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.clearLogs$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.clearLogs{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(BoxApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.getInstalledApps$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getInstalledApps{ result: Result<List<InstalledApp>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BoxApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.clashmiao.BoxHostApi.getAppIconBase64$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val packageNameArg = args[0] as String
            api.getAppIconBase64(packageNameArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(BoxApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(BoxApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
