// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsBoxApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsBoxApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsBoxApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashBoxApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashBoxApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashBoxApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// sing-box 调用入参 / 出参承载体。
///
/// Generated class from Pigeon that represents data sent in messages.
struct StartRequest: Hashable {
  var configPath: String
  var profileName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StartRequest? {
    let configPath = pigeonVar_list[0] as! String
    let profileName = pigeonVar_list[1] as! String

    return StartRequest(
      configPath: configPath,
      profileName: profileName
    )
  }
  func toList() -> [Any?] {
    return [
      configPath,
      profileName,
    ]
  }
  static func == (lhs: StartRequest, rhs: StartRequest) -> Bool {
    return deepEqualsBoxApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBoxApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConfigOptions: Hashable {
  var jsonOptions: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConfigOptions? {
    let jsonOptions = pigeonVar_list[0] as! String

    return ConfigOptions(
      jsonOptions: jsonOptions
    )
  }
  func toList() -> [Any?] {
    return [
      jsonOptions
    ]
  }
  static func == (lhs: ConfigOptions, rhs: ConfigOptions) -> Bool {
    return deepEqualsBoxApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBoxApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SelectOutboundRequest: Hashable {
  var groupTag: String
  var outboundTag: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SelectOutboundRequest? {
    let groupTag = pigeonVar_list[0] as! String
    let outboundTag = pigeonVar_list[1] as! String

    return SelectOutboundRequest(
      groupTag: groupTag,
      outboundTag: outboundTag
    )
  }
  func toList() -> [Any?] {
    return [
      groupTag,
      outboundTag,
    ]
  }
  static func == (lhs: SelectOutboundRequest, rhs: SelectOutboundRequest) -> Bool {
    return deepEqualsBoxApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBoxApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ValidateConfigRequest: Hashable {
  var path: String
  var tempPath: String
  var debug: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ValidateConfigRequest? {
    let path = pigeonVar_list[0] as! String
    let tempPath = pigeonVar_list[1] as! String
    let debug = pigeonVar_list[2] as! Bool

    return ValidateConfigRequest(
      path: path,
      tempPath: tempPath,
      debug: debug
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      tempPath,
      debug,
    ]
  }
  static func == (lhs: ValidateConfigRequest, rhs: ValidateConfigRequest) -> Bool {
    return deepEqualsBoxApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBoxApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ValidateConfigResult: Hashable {
  /// `null` 表示成功；非空字符串为人类可读错误。
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ValidateConfigResult? {
    let error: String? = nilOrValue(pigeonVar_list[0])

    return ValidateConfigResult(
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      error
    ]
  }
  static func == (lhs: ValidateConfigResult, rhs: ValidateConfigResult) -> Bool {
    return deepEqualsBoxApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashBoxApi(value: toList(), hasher: &hasher)
  }
}

private class BoxApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return StartRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return ConfigOptions.fromList(self.readValue() as! [Any?])
    case 131:
      return SelectOutboundRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return ValidateConfigRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return ValidateConfigResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class BoxApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? StartRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ConfigOptions {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? SelectOutboundRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ValidateConfigRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ValidateConfigResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BoxApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BoxApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BoxApiPigeonCodecWriter(data: data)
  }
}

class BoxApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = BoxApiPigeonCodec(readerWriter: BoxApiPigeonCodecReaderWriter())
}


/// Dart 调原生：sing-box 生命周期 + 状态变更。
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BoxHostApi {
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  func setup(baseDir: String, workingDir: String, tempDir: String, debug: Bool, completion: @escaping (Result<Void, Error>) -> Void)
  func validateConfig(req: ValidateConfigRequest, completion: @escaping (Result<ValidateConfigResult, Error>) -> Void)
  func changeConfigOptions(options: ConfigOptions, completion: @escaping (Result<Void, Error>) -> Void)
  func start(req: StartRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  func restart(req: StartRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func selectOutbound(req: SelectOutboundRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func urlTest(groupTag: String, completion: @escaping (Result<Void, Error>) -> Void)
  func generateFullConfig(path: String, completion: @escaping (Result<String?, Error>) -> Void)
  func clearLogs(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BoxHostApiSetup {
  static var codec: FlutterStandardMessageCodec { BoxApiPigeonCodec.shared }
  /// Sets up an instance of `BoxHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BoxHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.init\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initChannel.setMessageHandler(nil)
    }
    let setupChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.setup\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setupChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let baseDirArg = args[0] as! String
        let workingDirArg = args[1] as! String
        let tempDirArg = args[2] as! String
        let debugArg = args[3] as! Bool
        api.setup(baseDir: baseDirArg, workingDir: workingDirArg, tempDir: tempDirArg, debug: debugArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setupChannel.setMessageHandler(nil)
    }
    let validateConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.validateConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! ValidateConfigRequest
        api.validateConfig(req: reqArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      validateConfigChannel.setMessageHandler(nil)
    }
    let changeConfigOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.changeConfigOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeConfigOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! ConfigOptions
        api.changeConfigOptions(options: optionsArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      changeConfigOptionsChannel.setMessageHandler(nil)
    }
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! StartRequest
        api.start(req: reqArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let restartChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.restart\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      restartChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! StartRequest
        api.restart(req: reqArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      restartChannel.setMessageHandler(nil)
    }
    let selectOutboundChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.selectOutbound\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      selectOutboundChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reqArg = args[0] as! SelectOutboundRequest
        api.selectOutbound(req: reqArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      selectOutboundChannel.setMessageHandler(nil)
    }
    let urlTestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.urlTest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      urlTestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let groupTagArg = args[0] as! String
        api.urlTest(groupTag: groupTagArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      urlTestChannel.setMessageHandler(nil)
    }
    let generateFullConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.generateFullConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateFullConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.generateFullConfig(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateFullConfigChannel.setMessageHandler(nil)
    }
    let clearLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.clashmiao.BoxHostApi.clearLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearLogsChannel.setMessageHandler { _, reply in
        api.clearLogs { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearLogsChannel.setMessageHandler(nil)
    }
  }
}
